### ISSUE TITLE
cant download music

### ISSUE THREAD

**Issue by JYIG** [Yoshify/DiscJockey#1] opened 2024-01-01 14:26 UTC
[[Message   BepInEx] BepInEx 5.4.21..txt](https://github.com/Yoshify/DiscJockey/files/13804861/Message.BepInEx.BepInEx.5.4.21.txt)

I was able to attempt the download by inserting the link, but there has been no response no matter how long I wait afterward

**Comment by HeeyMonster** [comment] 2024-01-11 06:33
Same here, I have only this mod installed, and using V49, pretty much the same results. :0

**Comment by stdcall0** [comment] 2024-01-13 06:41
same here. I tried installing yt-dlp and add it to path, still not working.

**Comment by Yoshify** [comment] 2024-01-16 01:22
@JYIG , @HeeyMonster , @stdcall0 

I hope you haven't taken my silence as me ignoring the issue, I've actually been working quite hard to determine the root cause.
Turns out, the version of `System.Net.Http` included in Unity still uses `MonoWebRequestHandler` - and this really does not like double byte characters (accented characters, JP/CN/KR characters, etc.) in the hostname of the sending machine.
I've come up with a solution that will be in the next release and the automatic downloading of the necessary utilities for DiscJockey to function should just work again :)

**Closed** 2024-01-16 01:25 UTC

**Comment by frostguner** [comment] 2025-04-13 03:46
its happening again
